FROM nginx:1.13.6

LABEL Author="Keuller Magalhaes <keuller.magalhaes@gmail.com>"
LABEL Author="Luiz Otavio <luiz.otavio.aquino.menniti@gmail.com>"

ADD font-awesome /usr/share/nginx/html/font-awesome
ADD index.html /usr/share/nginx/html/index.html
ADD dist /usr/share/nginx/html/dist
